"""Generate RADAR.md from metadata plus the previous snapshot."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import (  # noqa: E402
    ROOT,
    compute_radar,
    load_config,
    load_metadata,
    load_tools,
    previous_snapshot,
    utcnow,
    validate_tools,
)

RADAR_PATH = ROOT / "RADAR.md"


def _bullet(tool: dict) -> str:
    extra = f" — {tool['reason']}" if tool.get("reason") else ""
    return f"- [{tool['name']}]({tool['url']}){extra}"


def build_radar(tools: list[dict], metadata: dict, previous: dict | None, config: dict) -> str:
    radar = compute_radar(tools, metadata, previous, config)
    today = utcnow().date().isoformat()
    lines = [
        "<!-- Generated by scripts/build_radar.py. Do not edit by hand. -->",
        "",
        f"# Radar ({today})",
        "",
    ]
    if metadata.get("incomplete"):
        lines += [
            "> Metadata is incomplete. Treat this radar as a partial signal.",
            "",
        ]
    if not radar["baseline"]:
        lines += [
            "No previous snapshot to compare against. New entries and Active stay empty until the next refresh.",
            "",
        ]

    sections = [
        ("New entries", radar["new_entries"], "Tools added to `data/tools.yaml` since the last snapshot."),
        ("Active this week", radar["active"], "Crossed a threshold: star jump, new release, or a cold repository pushed."),
        ("Possibly stale", radar["stale"], "Archived, or no push in about 18 months."),
        ("Watch", radar["watch"], "Fetch errors: missing repo, rename, or auth."),
    ]
    for title, items, hint in sections:
        lines += [f"## {title}", "", hint, ""]
        if items:
            lines.extend(_bullet(item) for item in items)
        else:
            lines.append("_None._")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    tools = load_tools()
    errors = validate_tools(tools)
    if errors:
        print("tools.yaml is invalid:", file=sys.stderr)
        for item in errors:
            print(f"  - {item}", file=sys.stderr)
        return 1
    metadata = load_metadata()
    previous = previous_snapshot()
    text = build_radar(tools, metadata, previous, load_config())
    RADAR_PATH.write_text(text, encoding="utf-8")
    print(f"Wrote {RADAR_PATH.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
