"""Generate README.md from tools.yaml and metadata.json."""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import (  # noqa: E402
    CATEGORIES,
    ROOT,
    active_tools,
    format_meta_suffix,
    is_retired,
    load_metadata,
    load_tools,
    tool_sort_key,
    validate_tools,
)

README_PATH = ROOT / "README.md"


def build_readme(tools: list[dict], metadata: dict) -> str:
    incomplete = metadata.get("incomplete")
    fetched = metadata.get("fetched_at", "")
    lines: list[str] = [
        "<!-- Generated by scripts/build_readme.py. Edit data/tools.yaml instead. -->",
        "",
        "# News-Rust-bioinformation",
        "",
        "A living catalog of Rust libraries, applications, workflows, and learning resources for computational biology.",
        "",
        "Within each category, tools are sorted by star count (highest first). Last-push date and name break ties. Rebuild with `python scripts/fetch_metadata.py` then `python scripts/build_readme.py`.",
        "",
    ]
    if incomplete:
        lines += [
            "> GitHub metadata is incomplete (missing token or a fetch error). Radar numbers may be stale.",
            "",
        ]
    if fetched:
        lines += [f"_Last metadata fetch: {fetched}_", ""]

    catalog = active_tools(tools)
    retired = [t for t in tools if is_retired(t)]

    lines += ["## Contents", ""]
    for slug, title in CATEGORIES:
        if any(t.get("category") == slug for t in catalog):
            anchor = title.lower().replace(" ", "-")
            lines.append(f"- [{title}](#{anchor})")
    if retired:
        lines.append("- [Retired](#retired)")
    lines += ["", "## Catalog", ""]

    for slug, title in CATEGORIES:
        group = [t for t in catalog if t.get("category") == slug]
        if not group:
            continue
        group = sorted(group, key=lambda t: tool_sort_key(t, metadata))
        lines += [f"### {title}", ""]
        for tool in group:
            suffix = format_meta_suffix(tool, metadata)
            lines.append(
                f"- [{tool['name']}]({tool['url']}) - {tool['description']}{suffix}"
            )
        lines.append("")

    if retired:
        retired = sorted(retired, key=lambda t: tool_sort_key(t, metadata))
        lines += [
            "## Retired",
            "",
            "Archived or otherwise removed from the living catalog. Kept here so radar history is not lost.",
            "",
        ]
        for tool in retired:
            suffix = format_meta_suffix(tool, metadata)
            lines.append(
                f"- [{tool['name']}]({tool['url']}) - {tool['description']}{suffix}"
            )
        lines.append("")

    lines += [
        "## Related",
        "",
        "- [sharkLoc/rust-in-bioinformatics](https://github.com/sharkLoc/rust-in-bioinformatics) - A collection of genomics CLI tools written in Rust.",
        "- [Are we bio yet?](https://rust4bio.github.io/arewebioyet/) - Earlier registry of Rust bioinformatics crates.",
        "- [awesome-rust Bioinformatics](https://github.com/rust-unofficial/awesome-rust#bioinformatics) - Short subsection in the general Rust awesome list.",
        "- [Awesome Bioinformatics](https://github.com/danielecook/Awesome-Bioinformatics) - Language-agnostic bioinformatics list.",
        "",
        "## Contributing",
        "",
        "See [CONTRIBUTING.md](CONTRIBUTING.md).",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    tools = load_tools()
    errors = validate_tools(tools)
    if errors:
        print("tools.yaml is invalid:", file=sys.stderr)
        for item in errors:
            print(f"  - {item}", file=sys.stderr)
        return 1
    metadata = load_metadata()
    text = build_readme(tools, metadata)
    README_PATH.write_text(text, encoding="utf-8")
    n_retired = sum(1 for t in tools if is_retired(t))
    print(f"Wrote {README_PATH.name} ({len(tools) - n_retired} catalog, {n_retired} retired)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
