use std::path::Path;

use crate::catalog::{load_yaml_list, utcnow, validate_tool_docs, value_to_tool, Tool};
use crate::config::{load_config, Config};
use crate::metadata::{load_metadata, previous_snapshot, Metadata};
use crate::paths;
use crate::radar::compute_radar;

fn bullet(tool: &Tool) -> String {
    let extra = tool
        .reason
        .as_deref()
        .map(|reason| format!(" — {reason}"))
        .unwrap_or_default();
    format!("- [{}]({}){extra}", tool.name, tool.url)
}

pub fn build_radar_markdown(
    tools: &[Tool],
    metadata: &Metadata,
    previous: Option<&Metadata>,
    config: &Config,
) -> String {
    let radar = compute_radar(tools, metadata, previous, config, None);
    let today = utcnow().date_naive().to_string();
    let mut lines = vec![
        "<!-- Generated by nrb build-radar. Do not edit by hand. -->".to_string(),
        String::new(),
        format!("# Radar ({today})"),
        String::new(),
    ];
    if metadata.incomplete {
        lines.push("> Metadata is incomplete. Treat this radar as a partial signal.".into());
        lines.push(String::new());
    }
    if !radar.baseline {
        lines.push("No previous snapshot to compare against. New entries and Active stay empty until the next refresh.".into());
        lines.push(String::new());
    }
    let sections = [
        (
            "New entries",
            &radar.new_entries,
            "Tools added to `data/tools.yaml` since the last snapshot.",
        ),
        (
            "Active this week",
            &radar.active,
            "Crossed a threshold: star jump, new release, or a cold repository pushed.",
        ),
        (
            "Possibly stale",
            &radar.stale,
            "Archived, or no push in about 18 months.",
        ),
        (
            "Watch",
            &radar.watch,
            "Fetch errors: missing repo, rename, or auth.",
        ),
    ];
    for (title, items, hint) in sections {
        lines.push(format!("## {title}"));
        lines.push(String::new());
        lines.push(hint.into());
        lines.push(String::new());
        if items.is_empty() {
            lines.push("_None._".into());
        } else {
            lines.extend(items.iter().map(bullet));
        }
        lines.push(String::new());
    }
    lines.join("\n")
}

pub fn cmd_build_radar(root: &Path) -> i32 {
    let docs = match load_yaml_list(&paths::tools_path(root)) {
        Ok(docs) => docs,
        Err(err) => {
            eprintln!("{err}");
            return 1;
        }
    };
    let errors = validate_tool_docs(&docs);
    if !errors.is_empty() {
        eprintln!("tools.yaml is invalid:");
        for item in errors {
            eprintln!("  - {item}");
        }
        return 1;
    }
    let tools: Vec<Tool> = docs.iter().filter_map(value_to_tool).collect();
    let metadata = load_metadata(&paths::metadata_path(root));
    let previous = previous_snapshot(&paths::snapshot_dir(root), None);
    let text = build_radar_markdown(
        &tools,
        &metadata,
        previous.as_ref(),
        &load_config(&paths::config_path(root)),
    );
    let path = root.join("RADAR.md");
    if let Err(err) = std::fs::write(&path, text) {
        eprintln!("{err}");
        return 1;
    }
    println!("Wrote RADAR.md");
    0
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Config, RadarConfig};
    use chrono::{TimeZone, Utc};
    use std::collections::BTreeMap;

    fn test_config() -> Config {
        Config {
            radar: RadarConfig {
                stale_months: 18,
                cold_inactive_months: 6,
                min_star_delta: 5,
                include_new_release: true,
                include_cold_repo_push: true,
            },
            snapshots_keep: 8,
        }
    }

    fn tool(name: &str, repo: &str) -> Tool {
        Tool {
            name: name.into(),
            url: format!("https://github.com/{repo}"),
            repo: Some(repo.into()),
            category: "core-libraries".into(),
            description: "Test.".into(),
            status: None,
            reason: None,
        }
    }

    fn rec(
        stars: Option<i64>,
        pushed_at: &str,
        archived: bool,
        latest_release_at: Option<&str>,
        error: Option<&str>,
    ) -> crate::metadata::RepoRecord {
        crate::metadata::RepoRecord {
            stars,
            pushed_at: if pushed_at.is_empty() {
                None
            } else {
                Some(pushed_at.into())
            },
            archived: Some(archived),
            latest_release_at: latest_release_at.map(str::to_string),
            latest_release_tag: None,
            error: error.map(str::to_string),
        }
    }

    fn now() -> chrono::DateTime<Utc> {
        Utc.with_ymd_and_hms(2026, 8, 30, 0, 0, 0).unwrap()
    }

    #[test]
    fn no_baseline_skips_new_and_active() {
        let tools = [tool("a", "o/a")];
        let mut repos = BTreeMap::new();
        repos.insert(
            "o/a".into(),
            rec(Some(10), "2026-08-29T00:00:00Z", false, None, None),
        );
        let current = Metadata {
            urls: vec![tools[0].url.clone()],
            repos,
            ..Metadata::default()
        };
        let radar = compute_radar(&tools, &current, None, &test_config(), Some(now()));
        assert!(!radar.baseline);
        assert!(radar.new_entries.is_empty());
        assert!(radar.active.is_empty());
    }

    #[test]
    fn new_entry_from_url_diff() {
        let old = tool("a", "o/a");
        let new = tool("b", "o/b");
        let previous = Metadata {
            urls: vec![old.url.clone()],
            ..Metadata::default()
        };
        let current = Metadata {
            urls: vec![old.url.clone(), new.url.clone()],
            ..Metadata::default()
        };
        let radar = compute_radar(
            &[old, new],
            &current,
            Some(&previous),
            &test_config(),
            Some(now()),
        );
        assert_eq!(
            radar
                .new_entries
                .iter()
                .map(|t| t.name.as_str())
                .collect::<Vec<_>>(),
            ["b"]
        );
    }

    #[test]
    fn star_delta_and_ordinary_push() {
        let t = tool("a", "o/a");
        let mut prev_repos = BTreeMap::new();
        prev_repos.insert(
            "o/a".into(),
            crate::metadata::RepoRecord {
                stars: Some(10),
                pushed_at: Some("2026-08-20T00:00:00Z".into()),
                archived: Some(false),
                latest_release_at: Some("2026-01-01T00:00:00Z".into()),
                latest_release_tag: None,
                error: None,
            },
        );
        let previous = Metadata {
            urls: vec![t.url.clone()],
            repos: prev_repos,
            ..Metadata::default()
        };
        let mut quiet_repos = BTreeMap::new();
        quiet_repos.insert(
            "o/a".into(),
            crate::metadata::RepoRecord {
                stars: Some(12),
                pushed_at: Some("2026-08-29T00:00:00Z".into()),
                archived: Some(false),
                latest_release_at: Some("2026-01-01T00:00:00Z".into()),
                latest_release_tag: None,
                error: None,
            },
        );
        let quiet = Metadata {
            urls: vec![t.url.clone()],
            repos: quiet_repos,
            ..Metadata::default()
        };
        let radar = compute_radar(
            &[t.clone()],
            &quiet,
            Some(&previous),
            &test_config(),
            Some(now()),
        );
        assert!(radar.active.is_empty());

        let mut jumped_repos = BTreeMap::new();
        jumped_repos.insert(
            "o/a".into(),
            crate::metadata::RepoRecord {
                stars: Some(20),
                pushed_at: Some("2026-08-29T00:00:00Z".into()),
                archived: Some(false),
                latest_release_at: Some("2026-01-01T00:00:00Z".into()),
                latest_release_tag: None,
                error: None,
            },
        );
        let jumped = Metadata {
            urls: vec![t.url.clone()],
            repos: jumped_repos,
            ..Metadata::default()
        };
        let radar = compute_radar(&[t], &jumped, Some(&previous), &test_config(), Some(now()));
        assert_eq!(radar.active.len(), 1);
        assert!(radar.active[0].reason.as_deref().unwrap().contains("stars"));
    }

    #[test]
    fn new_entry_not_also_active() {
        let old = tool("a", "o/a");
        let new = tool("b", "o/b");
        let previous = Metadata {
            urls: vec![old.url.clone()],
            ..Metadata::default()
        };
        let mut repos = BTreeMap::new();
        repos.insert(
            "o/b".into(),
            crate::metadata::RepoRecord {
                stars: Some(10),
                pushed_at: Some("2026-08-29T00:00:00Z".into()),
                archived: Some(false),
                latest_release_at: Some("2026-08-20T00:00:00Z".into()),
                latest_release_tag: Some("v1.0".into()),
                error: None,
            },
        );
        let current = Metadata {
            urls: vec![old.url.clone(), new.url.clone()],
            repos,
            ..Metadata::default()
        };
        let radar = compute_radar(
            &[old, new],
            &current,
            Some(&previous),
            &test_config(),
            Some(now()),
        );
        assert_eq!(
            radar
                .new_entries
                .iter()
                .map(|t| t.name.as_str())
                .collect::<Vec<_>>(),
            ["b"]
        );
        assert!(radar.active.is_empty());
    }

    #[test]
    fn retired_skipped_in_new_and_stale() {
        let live = tool("live", "o/live");
        let mut gone = tool("gone", "o/gone");
        gone.status = Some("retired".into());
        let previous = Metadata {
            urls: vec![live.url.clone()],
            ..Metadata::default()
        };
        let mut repos = BTreeMap::new();
        repos.insert(
            "o/live".into(),
            rec(Some(3), "2026-08-29T00:00:00Z", false, None, None),
        );
        repos.insert(
            "o/gone".into(),
            rec(Some(1), "2024-01-01T00:00:00Z", true, None, None),
        );
        let current = Metadata {
            urls: vec![live.url.clone(), gone.url.clone()],
            repos,
            ..Metadata::default()
        };
        let radar = compute_radar(
            &[live, gone],
            &current,
            Some(&previous),
            &test_config(),
            Some(now()),
        );
        assert!(radar.new_entries.is_empty());
        assert!(radar.stale.is_empty());
    }

    #[test]
    fn stale_and_watch() {
        let stale = tool("old", "o/old");
        let missing = tool("gone", "o/gone");
        let mut repos = BTreeMap::new();
        repos.insert(
            "o/old".into(),
            rec(Some(1), "2024-01-01T00:00:00Z", false, None, None),
        );
        repos.insert(
            "o/gone".into(),
            crate::metadata::RepoRecord {
                error: Some("not found".into()),
                ..crate::metadata::RepoRecord::default()
            },
        );
        let current = Metadata {
            urls: vec![stale.url.clone(), missing.url.clone()],
            repos: repos.clone(),
            ..Metadata::default()
        };
        let previous = Metadata {
            urls: vec![stale.url.clone(), missing.url.clone()],
            repos,
            ..Metadata::default()
        };
        let radar = compute_radar(
            &[stale, missing],
            &current,
            Some(&previous),
            &test_config(),
            Some(now()),
        );
        assert_eq!(
            radar
                .stale
                .iter()
                .map(|t| t.name.as_str())
                .collect::<Vec<_>>(),
            ["old"]
        );
        assert_eq!(
            radar
                .watch
                .iter()
                .map(|t| t.name.as_str())
                .collect::<Vec<_>>(),
            ["gone"]
        );
    }

    #[test]
    fn sorts_by_stars_then_push_then_name() {
        let tools = [
            tool("zeta", "o/zeta"),
            tool("alpha", "o/alpha"),
            tool("mid", "o/mid"),
            tool("recent-low", "o/recent-low"),
            tool("no-stars", "o/no-stars"),
            Tool {
                name: "orphan".into(),
                url: "https://example.org/orphan".into(),
                repo: None,
                category: "core-libraries".into(),
                description: "Test.".into(),
                status: None,
                reason: None,
            },
        ];
        let mut repos = BTreeMap::new();
        repos.insert(
            "o/zeta".into(),
            rec(Some(100), "2026-01-01T00:00:00Z", false, None, None),
        );
        repos.insert(
            "o/alpha".into(),
            rec(Some(100), "2026-01-01T00:00:00Z", false, None, None),
        );
        repos.insert(
            "o/mid".into(),
            rec(Some(50), "2026-08-01T00:00:00Z", false, None, None),
        );
        repos.insert(
            "o/recent-low".into(),
            rec(Some(10), "2026-08-29T00:00:00Z", false, None, None),
        );
        repos.insert(
            "o/no-stars".into(),
            crate::metadata::RepoRecord {
                stars: None,
                pushed_at: Some("2026-08-30T00:00:00Z".into()),
                archived: None,
                latest_release_at: None,
                latest_release_tag: None,
                error: None,
            },
        );
        let metadata = Metadata {
            repos,
            ..Metadata::default()
        };
        let mut ordered = tools.to_vec();
        ordered.sort_by_key(|t| crate::metadata::tool_sort_key(t, &metadata));
        assert_eq!(
            ordered.iter().map(|t| t.name.as_str()).collect::<Vec<_>>(),
            ["alpha", "zeta", "mid", "recent-low", "no-stars", "orphan"]
        );
    }
}
