use std::path::Path;

use chrono::{DateTime, Utc};

use crate::catalog::utcnow;
use crate::config::{load_config, Config};
use crate::metadata::{
    architecture_badge, calculate_activity, format_v2_badges, load_metadata, tooldef_sort_key,
    ActivityLevel, Metadata,
};
use crate::model::{Catalog, CategoryDef, ToolDef};
use crate::paths;
use crate::trends::{is_emerging, is_trending, load_trends, TrendsData};

pub fn build_readme_v2(
    catalog: &Catalog,
    metadata: &Metadata,
    trends: Option<&TrendsData>,
    config: &Config,
    now: DateTime<Utc>,
) -> String {
    let today_str = now.date_naive().to_string();
    let mut lines = vec![
        "<!--".into(),
        "Generated by nrb build-readme. Do not edit this file manually.".into(),
        "Edit data/tools.yaml instead.".into(),
        "-->".into(),
        String::new(),
        "# Rust Bioinformatics Radar 🦀🧬".into(),
        String::new(),
        "A continuously updated catalog and ecosystem radar for Rust libraries, applications, and infrastructure in bioinformatics and computational biology.".into(),
        String::new(),
        "> Automatically tracks repository activity, releases, ecosystem trends, and emerging projects.".into(),
        String::new(),
    ];

    // Stats bar
    let total_count = catalog.tools.len();
    let active_tools: Vec<&ToolDef> = catalog
        .tools
        .values()
        .filter(|t| t.is_active_in_catalog())
        .collect();
    let retired_tools: Vec<&ToolDef> = catalog.tools.values().filter(|t| t.is_retired()).collect();

    let active_repos_count = active_tools
        .iter()
        .filter(|t| {
            let rec = metadata.get_repo(&t.repository);
            calculate_activity(rec, &config.activity, now) == ActivityLevel::Active
        })
        .count();

    let native_count = active_tools
        .iter()
        .filter(|t| t.architecture.rust_role == crate::model::RustRole::Native)
        .count();

    let py_count = active_tools.iter().filter(|t| t.is_python_facing()).count();

    let published_count = active_tools
        .iter()
        .filter(|t| !t.publications.is_empty())
        .count();

    lines.push(format!(
        "**Projects:** {} · **Active:** {} · **Pure Rust:** {} · **Rust × Python:** {} · **Updated:** {}",
        total_count, active_repos_count, native_count, py_count, today_str
    ));
    lines.push(String::new());

    // Contents
    lines.push("## Contents".into());
    lines.push(String::new());
    lines.push("- [Ecosystem at a Glance](#ecosystem-at-a-glance)".into());
    lines.push("- [🔥 Trending](#-trending)".into());
    lines.push("- [🌱 Emerging Projects](#-emerging-projects)".into());
    lines.push("- [📖 Recommended Source Code](#-recommended-source-code)".into());
    lines.push("- [🧬 Bioinformatics Applications](#-bioinformatics-applications)".into());

    for (slug, cat) in &catalog.categories {
        if slug == "core-libraries"
            || slug == "sequence-io"
            || slug == "rust-python"
            || slug == "infrastructure"
            || slug == "learning"
        {
            continue;
        }
        let has_tools = active_tools.iter().any(|t| {
            let p = t.primary_category();
            p == slug || cat.children.contains_key(p)
        });
        if !has_tools {
            continue;
        }
        let anchor = heading_anchor(&cat.name);
        lines.push(format!("  - [{}](#{})", cat.name, anchor));
        for (child_slug, child) in &cat.children {
            let has_child_tools = active_tools
                .iter()
                .any(|t| t.primary_category() == child_slug);
            if has_child_tools {
                let child_anchor = heading_anchor(&child.name);
                lines.push(format!("    - [{}](#{})", child.name, child_anchor));
            }
        }
    }

    lines.push("- [🦀 Core Rust Libraries](#-core-rust-libraries)".into());
    lines.push("- [🐍 Rust × Python](#-rust--python)".into());
    lines.push("- [⚙️ Infrastructure & Workflows](#️-infrastructure--workflows)".into());
    lines.push("- [📚 Learning Resources](#-learning-resources)".into());
    if !retired_tools.is_empty() {
        lines.push("- [🗄️ Retired](#️-retired)".into());
    }
    lines.push("- [📊 Methodology & Activity](#-methodology--activity)".into());
    lines.push("- [🤝 Contributing](#-contributing)".into());
    lines.push(String::new());

    // Ecosystem at a Glance Table
    let emerging_count = active_tools
        .iter()
        .filter(|t| {
            if let Some(rec) = metadata.get_repo(&t.repository) {
                is_emerging(rec, config, now)
            } else {
                false
            }
        })
        .count();

    lines.push("## Ecosystem at a Glance".into());
    lines.push(String::new());
    lines.push("| Metric | Count |".into());
    lines.push("|---|---:|".into());
    lines.push(format!("| Cataloged projects | {} |", total_count));
    lines.push(format!("| Actively maintained | {} |", active_repos_count));
    lines.push(format!("| Pure Rust | {} |", native_count));
    lines.push(format!("| Rust × Python | {} |", py_count));
    lines.push(format!(
        "| Published software (with DOI/paper) | {} |",
        published_count
    ));
    lines.push(format!(
        "| Emerging projects (<150★, active) | {} |",
        emerging_count
    ));
    lines.push(String::new());

    // 🔥 Trending Section
    let mut trending_list: Vec<(&ToolDef, i64, f64, ActivityLevel)> = Vec::new();
    if let Some(tr) = trends {
        for tool in &active_tools {
            if let Some(rec) = metadata.get_repo(&tool.repository) {
                let trend = tr.repositories.get(&tool.repository);
                if is_trending(rec, trend, config) {
                    let gain = trend.map(|t| t.stars_30d).unwrap_or(0);
                    let growth = trend.map(|t| t.growth_30d).unwrap_or(0.0);
                    let act = calculate_activity(Some(rec), &config.activity, now);
                    trending_list.push((tool, gain, growth, act));
                }
            }
        }
    }
    trending_list.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| b.0.name.cmp(&a.0.name)));
    trending_list.truncate(config.readme.trending_limit);

    lines.push("## 🔥 Trending".into());
    lines.push(String::new());
    lines.push("Projects showing notable GitHub growth during the last 30 days.".into());
    lines.push(String::new());
    if trending_list.is_empty() {
        lines.push("_No trending projects crossed thresholds this period._".into());
    } else {
        lines.push("| Project | Primary Area | Stars | +30d | Activity |".into());
        lines.push("|---|---|---:|---:|---|".into());
        for (tool, gain, _, act) in trending_list {
            let stars = metadata
                .get_repo(&tool.repository)
                .and_then(|r| r.stars)
                .unwrap_or(0);
            let area_name = resolve_category_name(&tool.category.primary, &catalog.categories);
            lines.push(format!(
                "| [{}]({}) | {} | {} | +{} | {} |",
                tool.name,
                tool.effective_url(),
                area_name,
                stars,
                gain,
                act.emoji()
            ));
        }
    }
    lines.push(String::new());

    // 🌱 Emerging Section
    let mut emerging_list: Vec<(&ToolDef, i64, ActivityLevel)> = Vec::new();
    for tool in &active_tools {
        if let Some(rec) = metadata.get_repo(&tool.repository) {
            if is_emerging(rec, config, now) {
                let stars = rec.stars.unwrap_or(0);
                let act = calculate_activity(Some(rec), &config.activity, now);
                emerging_list.push((tool, stars, act));
            }
        }
    }
    emerging_list.sort_by(|a, b| b.1.cmp(&a.1).then_with(|| a.0.name.cmp(&b.0.name)));
    emerging_list.truncate(config.readme.emerging_limit);

    lines.push("## 🌱 Emerging Projects".into());
    lines.push(String::new());
    lines.push(
        "Recently active Rust bioinformatics projects that are still relatively new or under 150 stars, but worth watching.".into(),
    );
    lines.push(String::new());
    if emerging_list.is_empty() {
        lines.push("_No emerging projects recorded._".into());
    } else {
        lines.push("| Project | Primary Area | Stars | Activity | Description |".into());
        lines.push("|---|---|---:|---|---|".into());
        for (tool, stars, act) in emerging_list {
            let area_name = resolve_category_name(&tool.category.primary, &catalog.categories);
            lines.push(format!(
                "| [{}]({}) | {} | {} | {} | {} |",
                tool.name,
                tool.effective_url(),
                area_name,
                stars,
                act.emoji(),
                tool.description
            ));
        }
    }
    lines.push(String::new());

    // 📖 Recommended Source Code
    let mut source_picks: Vec<&ToolDef> = active_tools
        .iter()
        .copied()
        .filter(|t| t.learning.as_ref().map(|l| l.recommended).unwrap_or(false))
        .collect();
    source_picks.sort_by_key(|t| tooldef_sort_key(t, metadata));
    source_picks.truncate(config.readme.source_picks_limit);

    lines.push("## 📖 Recommended Source Code".into());
    lines.push(String::new());
    lines.push(
        "Selected high-quality Rust codebases recommended for studying clean software architecture, high-throughput parsing, and biological algorithms.".into(),
    );
    lines.push(String::new());
    if !source_picks.is_empty() {
        lines.push("| Project | Recommended Focus & Topics | Level | Architecture |".into());
        lines.push("|---|---|---|---|".into());
        for tool in source_picks {
            let learning = tool.learning.as_ref().unwrap();
            let topics = learning.topics.join(", ");
            let level_str = match learning.level {
                Some(crate::model::LearningLevel::Beginner) => "Beginner",
                Some(crate::model::LearningLevel::Intermediate) => "Intermediate",
                Some(crate::model::LearningLevel::Advanced) => "Advanced",
                None => "General",
            };
            let arch = architecture_badge(tool);
            lines.push(format!(
                "| [{}]({}) | {} | {} | `{}` |",
                tool.name,
                tool.effective_url(),
                topics,
                level_str,
                arch
            ));
        }
        lines.push(String::new());
    }

    // Helper closure to format a list of tools
    let format_tool_item = |tool: &ToolDef| -> String {
        let badges = format_v2_badges(tool, metadata, &config.activity, now);
        let mut papers_md = Vec::new();
        for p in &tool.publications {
            let label = if let Some(ref d) = p.doi {
                format!("DOI: {d}")
            } else {
                "Paper".to_string()
            };
            let url = p.url.as_deref().unwrap_or("#");
            papers_md.push(format!("[{label}]({url})"));
        }
        let papers_str = if papers_md.is_empty() {
            String::new()
        } else {
            format!(" · {}", papers_md.join(" · "))
        };

        format!(
            "- **[{}]({})** — {}{}{}",
            tool.name,
            tool.effective_url(),
            tool.description,
            badges,
            papers_str
        )
    };

    // 🧬 Bioinformatics Applications
    lines.push("## 🧬 Bioinformatics Applications".into());
    lines.push(String::new());

    // Render non-core categories
    for (slug, cat) in &catalog.categories {
        if slug == "core-libraries"
            || slug == "sequence-io"
            || slug == "rust-python"
            || slug == "infrastructure"
            || slug == "learning"
        {
            continue;
        }
        if cat.is_section() {
            let section_has_tools = active_tools
                .iter()
                .any(|t| cat.children.contains_key(t.primary_category()));
            if !section_has_tools {
                continue;
            }
            lines.push(format!("### {}", cat.name));
            if let Some(ref d) = cat.description {
                lines.push(String::new());
                lines.push(format!("_{d}_"));
            }
            lines.push(String::new());

            for (child_slug, child) in &cat.children {
                let mut group: Vec<&ToolDef> = active_tools
                    .iter()
                    .copied()
                    .filter(|t| t.primary_category() == child_slug)
                    .collect();
                if group.is_empty() {
                    continue;
                }
                group.sort_by_key(|t| tooldef_sort_key(t, metadata));
                lines.push(format!("#### {}", child.name));
                lines.push(String::new());
                for t in group {
                    lines.push(format_tool_item(t));
                }
                lines.push(String::new());
            }
        } else {
            let mut group: Vec<&ToolDef> = active_tools
                .iter()
                .copied()
                .filter(|t| t.primary_category() == slug)
                .collect();
            if group.is_empty() {
                continue;
            }
            group.sort_by_key(|t| tooldef_sort_key(t, metadata));
            lines.push(format!("### {}", cat.name));
            if let Some(ref d) = cat.description {
                lines.push(String::new());
                lines.push(format!("_{d}_"));
            }
            lines.push(String::new());
            for t in group {
                lines.push(format_tool_item(t));
            }
            lines.push(String::new());
        }
    }

    // 🦀 Core Rust Libraries
    lines.push("## 🦀 Core Rust Libraries".into());
    lines.push(String::new());
    for cat_slug in &["core-libraries", "sequence-io"] {
        if let Some(cat) = catalog.categories.get(*cat_slug) {
            let mut group: Vec<&ToolDef> = active_tools
                .iter()
                .copied()
                .filter(|t| t.primary_category() == *cat_slug)
                .collect();
            if !group.is_empty() {
                group.sort_by_key(|t| tooldef_sort_key(t, metadata));
                lines.push(format!("### {}", cat.name));
                lines.push(String::new());
                for t in group {
                    lines.push(format_tool_item(t));
                }
                lines.push(String::new());
            }
        }
    }

    // 🐍 Rust × Python
    lines.push("## 🐍 Rust × Python".into());
    lines.push(String::new());
    lines.push(
        "Python packages and hybrid ecosystems accelerated by high-performance Rust cores.".into(),
    );
    lines.push(String::new());
    let mut py_tools: Vec<&ToolDef> = active_tools
        .iter()
        .copied()
        .filter(|t| t.is_python_facing())
        .collect();
    if py_tools.is_empty() {
        lines.push("_No Python hybrid tools currently indexed._".into());
    } else {
        py_tools.sort_by_key(|t| tooldef_sort_key(t, metadata));
        for t in py_tools {
            lines.push(format_tool_item(t));
        }
    }
    lines.push(String::new());

    // ⚙️ Infrastructure & Workflows
    if let Some(_cat) = catalog.categories.get("infrastructure") {
        let mut group: Vec<&ToolDef> = active_tools
            .iter()
            .copied()
            .filter(|t| t.primary_category() == "infrastructure")
            .collect();
        if !group.is_empty() {
            group.sort_by_key(|t| tooldef_sort_key(t, metadata));
            lines.push("## ⚙️ Infrastructure & Workflows".into());
            lines.push(String::new());
            for t in group {
                lines.push(format_tool_item(t));
            }
            lines.push(String::new());
        }
    }

    // 📚 Learning Resources
    if let Some(_cat) = catalog.categories.get("learning") {
        let mut group: Vec<&ToolDef> = active_tools
            .iter()
            .copied()
            .filter(|t| t.primary_category() == "learning")
            .collect();
        if !group.is_empty() {
            group.sort_by_key(|t| tooldef_sort_key(t, metadata));
            lines.push("## 📚 Learning Resources".into());
            lines.push(String::new());
            for t in group {
                lines.push(format_tool_item(t));
            }
            lines.push(String::new());
        }
    }

    // 🗄️ Retired
    if !retired_tools.is_empty() {
        let mut group = retired_tools;
        group.sort_by_key(|t| tooldef_sort_key(t, metadata));
        lines.push("## 🗄️ Retired".into());
        lines.push(String::new());
        lines.push(
            "Archived or superseded projects retained to preserve ecosystem lineage and radar history.".into(),
        );
        lines.push(String::new());
        for t in group {
            lines.push(format_tool_item(t));
        }
        lines.push(String::new());
    }

    // Methodology & Activity
    lines.push("## 📊 Methodology & Activity".into());
    lines.push(String::new());
    lines.push(
        "Activity badges are updated automatically via daily GitHub metadata tracking:".into(),
    );
    lines.push(String::new());
    lines.push("- `🟢 Active`: Pushed to within the last 90 days.".into());
    lines.push("- `🟡 Maintained`: Pushed to within 91–365 days.".into());
    lines.push("- `🟠 Quiet`: Pushed to within 366–730 days (1–2 years).".into());
    lines.push("- `🔴 Inactive`: No push for over 2 years.".into());
    lines.push("- `⚫ Archived`: Repository is officially archived on GitHub.".into());
    lines.push(String::new());

    // Related & Contributing
    lines.push("## 🤝 Contributing".into());
    lines.push(String::new());
    lines.push("Contributions are welcome! Please see [CONTRIBUTING.md](CONTRIBUTING.md).".into());
    lines.push(String::new());
    lines.push("To add or update a tool:".into());
    lines.push(
        "1. Edit `data/tools.yaml` (follow the schema in `schema/tools.schema.json`).".into(),
    );
    lines.push("2. Run `nrb validate` to check schema integrity.".into());
    lines.push("3. Open a Pull Request.".into());
    lines.push(String::new());

    lines.push("## 🔗 Related Resources".into());
    lines.push(String::new());
    lines.push(
        "- [Weekly Ecosystem Radar](RADAR.md) — Weekly activity, new releases, and trends.".into(),
    );
    lines.push("- [sharkLoc/rust-in-bioinformatics](https://github.com/sharkLoc/rust-in-bioinformatics) — Genomics CLI tools in Rust.".into());
    lines.push("- [Are we bio yet?](https://rust4bio.github.io/arewebioyet/) — Earlier registry of Rust bioinformatics crates.".into());
    lines.push("- [Awesome Bioinformatics](https://github.com/danielecook/Awesome-Bioinformatics) — General bioinformatics software list.".into());
    lines.push(String::new());

    lines.join("\n")
}

pub fn heading_anchor(title: &str) -> String {
    title
        .to_lowercase()
        .replace([' ', '/', '×'], "-")
        .replace(|c: char| !c.is_ascii_alphanumeric() && c != '-', "")
}

fn resolve_category_name(
    slug: &str,
    categories: &indexmap::IndexMap<String, CategoryDef>,
) -> String {
    if let Some(cat) = categories.get(slug) {
        return cat.name.clone();
    }
    for cat in categories.values() {
        if let Some(child) = cat.children.get(slug) {
            return child.name.clone();
        }
    }
    slug.to_string()
}

pub fn cmd_build_readme(root: &Path) -> i32 {
    let tools_path = paths::tools_path(root);
    let catalog = match crate::validate::load_and_validate(&tools_path) {
        Ok((cat, report)) => {
            if !report.is_valid() {
                eprintln!("tools.yaml has validation errors:");
                for err in report.errors {
                    eprintln!("  - {err}");
                }
                return 1;
            }
            cat
        }
        Err(err) => {
            eprintln!("Failed to load catalog: {err}");
            return 1;
        }
    };

    let metadata = load_metadata(&paths::metadata_path(root));
    let trends = load_trends(&paths::trends_path(root));
    let config = load_config(&paths::config_path(root));
    let now = utcnow();

    let content = build_readme_v2(&catalog, &metadata, trends.as_ref(), &config, now);
    let readme_path = root.join("README.md");
    if let Err(e) = std::fs::write(&readme_path, content) {
        eprintln!("Failed to write README.md: {e}");
        return 1;
    }

    let retired_count = catalog.tools.values().filter(|t| t.is_retired()).count();
    println!(
        "Successfully wrote README.md ({} active tools, {} retired tools)",
        catalog.tools.len() - retired_count,
        retired_count
    );
    0
}
