use std::path::Path;

use crate::catalog::{
    active_tools, heading_anchor, load_yaml_list, validate_tool_docs, value_to_tool, Category,
    Tool, CATEGORIES,
};
use crate::metadata::{format_meta_suffix, load_metadata, tool_sort_key, Metadata};
use crate::paths;

pub fn build_readme(tools: &[Tool], metadata: &Metadata) -> String {
    let incomplete = metadata.incomplete;
    let fetched = metadata.fetched_at.as_str();
    let mut lines = vec![
        "<!-- Generated by nrb build-readme. Edit data/tools.yaml instead. -->".to_string(),
        String::new(),
        "# News-Rust-bioinformation".into(),
        String::new(),
        "A living catalog of Rust libraries, applications, workflows, and learning resources for computational biology.".into(),
        String::new(),
        "Within each category, tools are sorted by star count (highest first). Last-push date and name break ties. Rebuild with `nrb fetch-metadata` then `nrb build-readme`.".into(),
        String::new(),
    ];
    if incomplete {
        lines.push("> GitHub metadata is incomplete (missing token or a fetch error). Radar numbers may be stale.".into());
        lines.push(String::new());
    }
    if !fetched.is_empty() {
        lines.push(format!("_Last metadata fetch: {fetched}_"));
        lines.push(String::new());
    }

    let catalog: Vec<&Tool> = active_tools(tools);
    let mut retired: Vec<&Tool> = tools.iter().filter(|tool| tool.is_retired()).collect();

    fn section_has_tools(node: &Category, catalog: &[&Tool]) -> bool {
        if node.is_section() {
            node.children
                .iter()
                .any(|child| section_has_tools(child, catalog))
        } else {
            catalog.iter().any(|tool| tool.category == node.slug)
        }
    }

    let append_tool_list = |group: Vec<&Tool>, lines: &mut Vec<String>| {
        let mut group = group;
        group.sort_by_key(|tool| tool_sort_key(tool, metadata));
        for tool in group {
            let suffix = format_meta_suffix(tool, metadata);
            lines.push(format!(
                "- [{}]({}) - {}{suffix}{}",
                tool.name,
                tool.url,
                tool.description,
                tool.paper_links_markdown()
            ));
        }
    };

    lines.push("## Contents".into());
    lines.push(String::new());
    for node in CATEGORIES {
        if !section_has_tools(node, &catalog) {
            continue;
        }
        lines.push(format!(
            "- [{}](#{})",
            node.title,
            heading_anchor(node.title)
        ));
        if node.is_section() {
            for child in node.children {
                lines.push(format!(
                    "  - [{}](#{})",
                    child.title,
                    heading_anchor(child.title)
                ));
            }
        }
    }
    if !retired.is_empty() {
        lines.push("- [Retired](#retired)".into());
    }
    lines.push(String::new());
    lines.push("## Catalog".into());
    lines.push(String::new());

    for node in CATEGORIES {
        if !section_has_tools(node, &catalog) {
            continue;
        }
        if node.is_section() {
            lines.push(format!("### {}", node.title));
            lines.push(String::new());
            for child in node.children {
                let group: Vec<&Tool> = catalog
                    .iter()
                    .copied()
                    .filter(|tool| tool.category == child.slug)
                    .collect();
                lines.push(format!("#### {}", child.title));
                lines.push(String::new());
                if !group.is_empty() {
                    append_tool_list(group, &mut lines);
                }
                lines.push(String::new());
            }
            continue;
        }
        let group: Vec<&Tool> = catalog
            .iter()
            .copied()
            .filter(|tool| tool.category == node.slug)
            .collect();
        lines.push(format!("### {}", node.title));
        lines.push(String::new());
        append_tool_list(group, &mut lines);
        lines.push(String::new());
    }

    if !retired.is_empty() {
        retired.sort_by_key(|tool| tool_sort_key(tool, metadata));
        lines.push("## Retired".into());
        lines.push(String::new());
        lines.push("Archived or otherwise removed from the living catalog. Kept here so radar history is not lost.".into());
        lines.push(String::new());
        for tool in retired {
            let suffix = format_meta_suffix(tool, metadata);
            lines.push(format!(
                "- [{}]({}) - {}{suffix}{}",
                tool.name,
                tool.url,
                tool.description,
                tool.paper_links_markdown()
            ));
        }
        lines.push(String::new());
    }

    lines.extend([
        "## Related".into(),
        String::new(),
        "- [sharkLoc/rust-in-bioinformatics](https://github.com/sharkLoc/rust-in-bioinformatics) - A collection of genomics CLI tools written in Rust.".into(),
        "- [Are we bio yet?](https://rust4bio.github.io/arewebioyet/) - Earlier registry of Rust bioinformatics crates.".into(),
        "- [awesome-rust Bioinformatics](https://github.com/rust-unofficial/awesome-rust#bioinformatics) - Short subsection in the general Rust awesome list.".into(),
        "- [Awesome Bioinformatics](https://github.com/danielecook/Awesome-Bioinformatics) - Language-agnostic bioinformatics list.".into(),
        String::new(),
        "## Contributing".into(),
        String::new(),
        "See [CONTRIBUTING.md](CONTRIBUTING.md).".into(),
        String::new(),
    ]);
    lines.join("\n")
}

pub fn cmd_build_readme(root: &Path) -> i32 {
    let docs = match load_yaml_list(&paths::tools_path(root)) {
        Ok(docs) => docs,
        Err(err) => {
            eprintln!("{err}");
            return 1;
        }
    };
    let errors = validate_tool_docs(&docs);
    if !errors.is_empty() {
        eprintln!("tools.yaml is invalid:");
        for item in errors {
            eprintln!("  - {item}");
        }
        return 1;
    }
    let tools: Vec<Tool> = docs.iter().filter_map(value_to_tool).collect();
    let metadata = load_metadata(&paths::metadata_path(root));
    let text = build_readme(&tools, &metadata);
    let path = root.join("README.md");
    if let Err(err) = std::fs::write(&path, text) {
        eprintln!("{err}");
        return 1;
    }
    let n_retired = tools.iter().filter(|tool| tool.is_retired()).count();
    println!(
        "Wrote README.md ({} catalog, {} retired)",
        tools.len() - n_retired,
        n_retired
    );
    0
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::catalog::valid_categories;

    #[test]
    fn bacterial_section_is_not_a_tool_category() {
        assert_eq!(CATEGORIES[0].slug, "crispr");
        assert_eq!(CATEGORIES[1].slug, "microbial-bioinformatics");
        assert!(CATEGORIES[1].is_section());
        assert!(!valid_categories().contains("microbial-bioinformatics"));
        for slug in [
            "bacterial-assembly",
            "bacterial-annotation",
            "prokaryotic-transcriptome",
            "metagenomics",
            "phage-defense",
            "resistance-genes",
            "transposons",
        ] {
            assert!(valid_categories().contains(slug));
        }
    }

    #[test]
    fn readme_lists_section_then_children() {
        let tools = [Tool {
            name: "demo".into(),
            url: "https://example.org/demo".into(),
            repo: None,
            category: "bacterial-assembly".into(),
            description: "Test.".into(),
            status: None,
            reason: None,
            papers: vec![],
        }];
        let text = build_readme(&tools, &Metadata::default());
        assert!(text.contains("### Microbial Bioinformatics"));
        assert!(text.contains("#### Bacterial Genome Assembly"));
        assert!(text.contains("#### Metagenomics"));
        assert!(text.contains("#### Phage Defense Systems"));
        assert!(text.contains("- [Microbial Bioinformatics](#microbial-bioinformatics)"));
        assert!(text.contains("  - [Genome Annotation](#genome-annotation)"));
        let crispr = text.find("### CRISPR");
        let microbial = text.find("### Microbial Bioinformatics").unwrap();
        let core = text.find("### Core Libraries").unwrap_or(text.len());
        assert!(microbial < core);
        if let Some(crispr) = crispr {
            assert!(crispr < microbial);
        }
        let contents = text.split("## Catalog").next().unwrap();
        assert!(!contents.contains("\n- [Metagenomics](#metagenomics)\n"));
        assert!(text.contains("  - [Metagenomics](#metagenomics)"));
    }

    #[test]
    fn readme_appends_paper_markdown_links() {
        use crate::catalog::Paper;
        let tools = [
            Tool {
                name: "salmon".into(),
                url: "https://github.com/COMBINE-lab/salmon".into(),
                repo: Some("COMBINE-lab/salmon".into()),
                category: "single-cell-and-rna".into(),
                description: "Transcript-level RNA-seq quantification using selective alignment.".into(),
                status: None,
                reason: None,
                papers: vec![Paper {
                    title: "Salmon provides fast and bias-aware quantification of transcript expression.".into(),
                    url: "https://doi.org/10.1038/nmeth.4197".into(),
                }],
            },
            Tool {
                name: "plain".into(),
                url: "https://example.org/plain".into(),
                repo: None,
                category: "core-libraries".into(),
                description: "No literature.".into(),
                status: None,
                reason: None,
                papers: vec![],
            },
            Tool {
                name: "old".into(),
                url: "https://example.org/old".into(),
                repo: None,
                category: "core-libraries".into(),
                description: "Retired with a paper.".into(),
                status: Some("retired".into()),
                reason: None,
                papers: vec![
                    Paper {
                        title: "First paper.".into(),
                        url: "https://doi.org/10.1093/bioinformatics/btr167".into(),
                    },
                    Paper {
                        title: "Second paper.".into(),
                        url: "https://doi.org/10.1186/s40168-019-0684-8".into(),
                    },
                ],
            },
        ];
        let text = build_readme(&tools, &Metadata::default());
        assert!(text.contains(
            "- [salmon](https://github.com/COMBINE-lab/salmon) - Transcript-level RNA-seq quantification using selective alignment. · [Salmon provides fast and bias-aware quantification of transcript expression.](https://doi.org/10.1038/nmeth.4197)"
        ));
        assert!(text.contains("- [plain](https://example.org/plain) - No literature."));
        assert!(!text.contains("- [plain](https://example.org/plain) - No literature. ·"));
        assert!(text.contains(
            "- [old](https://example.org/old) - Retired with a paper. · [First paper.](https://doi.org/10.1093/bioinformatics/btr167) · [Second paper.](https://doi.org/10.1186/s40168-019-0684-8)"
        ));
    }
}
